export const GAMES_SORT_COMPLETION = "GAMES_SORT_COMPLETION";
export const GAMES_SORT_PINNED = "GAMES_SORT_PINNED";
export const GAMES_SORT_STARTED = "GAMES_SORT_STARTED";
export const GAMES_VIEW_LARGE = "GAMES_VIEW_LARGE";
export const GAMES_VIEW_SMALL = "GAMES_VIEW_SMALL";

export const GAME_SORT_ALL = "GAME_SORT_ALL";
export const GAME_SORT_LOCKED = "GAME_SORT_LOCKED";
export const GAME_SORT_UNLOCKED = "GAME_SORT_ALL";
export const GAME_SORT_AZ = "GAME_SORT_AZ";
export const GAME_SORT_ZA = "GAME_SORT_ZA";
export const GAME_VIEW_LARGE = "GAME_VIEW_LARGE";
export const GAME_VIEW_SMALL = "GAME_VIEW_SMALL";
